<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Loan Calculator Monthly</title>
</head>
<body>
<table style="width:100%">
RRSO:
Całkowity koszt kredytu (kapitał + odsetki):
    <tr>
        <th>Numer miesiąca</th>
        <th>Kwota raty</th>
        <th>Kwota pozostała do spłaty</th>
    </tr>
    <tr>
        <td>aaaa</td>
        <td>bbbb</td>
        <td>cccc</td>
    </tr>
</table>
</body>
</html>